In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import models,layers
from sklearn.model_selection import train_test_split
from tensorflow.keras.regularizers import l2


In [ ]:
dataset = pd.read_csv('/kaggle/input/creditcardfraud/creditcard.csv')

In [ ]:
dataset=dataset.sample(frac=1)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 284807 entries, 223135 to 222887
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21  

In [ ]:
dataset.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  1.191536e-15  3.316250e-16 -1.394378e-15  2.111070e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   1.004417e-15  1.493492e-15 -5.832726e-16  1.286131e-16 -2.393007e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   ...  1.521338e-16 -3.497662e-16  2.700351e-16  4.484872e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   5.206915e-16  1.687119e-15 -3.766087e-16 -1.171763e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [ ]:
dataset.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
Time_mean=dataset['Time'].mean(axis=0)
Time_std=dataset['Time'].std(axis=0)
dataset['Time']-=Time_mean
dataset['Time']/=Time_std

In [ ]:
Amount_mean=dataset['Amount'].mean(axis=0)
Amount_std=dataset['Amount'].std(axis=0)
dataset['Amount']-=Amount_mean
dataset['Amount']/=Amount_std

In [ ]:
dataset['Time']

223135    1.020131
273945    1.494355
109722   -0.490646
45227    -1.106736
64308    -0.920458
            ...   
221886    1.009139
233831    1.114134
194962    0.758677
247522    1.237996
222887    1.018110
Name: Time, Length: 284807, dtype: float64

In [ ]:
dataset['Amount']

223135   -0.309250
273945   -0.333718
109722   -0.246280
45227     1.310372
64308    -0.282063
            ...   
221886   -0.074043
233831    0.545859
194962   -0.277665
247522    0.509157
222887   -0.345313
Name: Amount, Length: 284807, dtype: float64

In [ ]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
x

array([[ 1.02013122, -3.1796052 ,  2.63643198, ..., -0.16802724,
        -0.11566516, -0.3092499 ],
       [ 1.49435483, -0.54516499,  1.50946795, ...,  0.31595952,
         0.18063419, -0.33371815],
       [-0.4906458 ,  1.08216634, -0.17989176, ...,  0.06194041,
         0.02338179, -0.24628015],
       ...,
       [ 0.7586765 , -0.00556088, -0.43787704, ...,  0.18917215,
         0.18232742, -0.27766508],
       [ 1.23799612,  1.7557593 , -0.26901108, ..., -0.30980591,
        -0.09969845,  0.50915691],
       [ 1.01810967, -2.15900516,  0.52888106, ..., -0.20127974,
        -0.42818228, -0.34531258]])

In [ ]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 0)
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.3, random_state=0)

In [ ]:
x_test

array([[-0.17218738, -0.52498873,  0.90272759, ...,  0.13235988,
         0.13635761, -0.32564203],
       [ 1.01667773,  2.18860472, -0.51086142, ..., -0.05833737,
        -0.06264866, -0.31724606],
       [ 0.77874467, -0.67696301,  1.15209322, ..., -0.1156908 ,
         0.05828432, -0.31328796],
       ...,
       [-0.25085965, -0.40627089,  1.09509215, ...,  0.26934585,
         0.12192596, -0.34611219],
       [ 0.92878211,  1.86574183,  0.38329124, ..., -0.02632134,
        -0.0222563 , -0.23220692],
       [-0.48011686, -1.21514527, -0.14762331, ..., -0.23438954,
         0.19864582, -0.23888371]])

In [ ]:
model=models.Sequential()
model.add(layers.Dense(6, kernel_regularizer=l2(0.01), activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(6, kernel_regularizer=l2(0.01), activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))
model.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_val, y_val))

Epoch 1/5
4985/4985 [==============================] - 10s 2ms/step - loss: 0.1323 - accuracy: 0.9978 - val_loss: 0.0077 - val_accuracy: 0.9983
Epoch 2/5
4985/4985 [==============================] - 9s 2ms/step - loss: 0.0081 - accuracy: 0.9982 - val_loss: 0.0070 - val_accuracy: 0.9983
Epoch 3/5
4985/4985 [==============================] - 9s 2ms/step - loss: 0.0063 - accuracy: 0.9989 - val_loss: 0.0064 - val_accuracy: 0.9992
Epoch 4/5
4985/4985 [==============================] - 9s 2ms/step - loss: 0.0065 - accuracy: 0.9991 - val_loss: 0.0061 - val_accuracy: 0.9993
Epoch 5/5
4985/4985 [==============================] - 9s 2ms/step - loss: 0.0068 - accuracy: 0.9989 - val_loss: 0.0059 - val_accuracy: 0.9993


In [ ]:
model.evaluate(x_test,y_test)

1781/1781 [==============================] - 2s 971us/step - loss: 0.0052 - accuracy: 0.9992


[0.005247646011412144, 0.9992275834083557]

In [ ]:
predictions=model.predict(x_test)
predictions[19787]

array([0.70571035], dtype=float32)

In [ ]:
y_test[19787]

1